$(clickMe).on('click',function(elm){
    elm.stopPropagation()
    $(popover).toggle('show')
    $(document).one('click',function(){
    })
})
popover.addEventListener('click',(elm)=>{
    elm.stopPropagation()
})