$(clickMe).on('click',function(elm){
    elm.stopPropagation()
    $(popover).toggle('active')
})
popover.addEventListener('click',(elm)=>{
    elm.stopPropagation()
})
$(document).on('click',function(){
    $(popover).hide()
})